title: Remy the Rat: The Autobiography
author: Remy (The Rat)
theme: minima
email: remy@gustoinc.com
description: > # this means to ignore newlines until "baseurl:"
  Ratatouille is a summer vegetable stew that originated as a French Provencal dish from Nice.
  It's a stew of zucchini, peppers, tomatoes and eggplant, with herbs and spices and some onions and garlic usually thrown in for good measure.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
